service: default
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: .*
  script: main.app

libraries:
- name: webapp2
  version: "2.5.2"

skip_files:
  - ^(.*/)?app\.yaml
  - ^(.*/)?app\.yml
  - ^(.*/)?#.*#
  - ^(.*/)?.*~
  - ^(.*/)?.*\.py[co]
  - ^(.*/)?.*/RCS/.*
  - ^(.*/)?\..*
  - ^(.*/)?tests$
  - ^(.*/)?test$
  - ^test/(.*/)?
  - ^COPYING.LESSER
  - ^README\..*
  - \.gitignore
  - \.travis.yml
  - \gae.json.enc
  - ^(.*/)?.lock
  - ^(.*/)?.log
  - \gatsby-config.js
  - \gatsby-node.js
  - \gatsby-ssr.js
  - \README.md
  - \LICENSE
  - ^\.git/.*
  - \.*\.lint$
  - ^fabfile\.py
  - ^testrunner\.py
  - ^grunt\.js
  - ^node_modules/(.*/)?
  - ^src/(.*/)?
  - ^.cache/(.*/)?
