service: default
runtime: nodejs20

# Simple static file serving - let Next.js handle everything
handlers:
  # Serve all static files from the out directory
  - url: /(.*)
    static_files: out/\1
    upload: out/.*
    expiration: '0m'
