service: default
runtime: nodejs20

# Static file serving for Next.js export
handlers:
  # Static assets with proper caching
  - url: /_next/static/(.*)
    static_files: out/_next/static/\1
    upload: out/_next/static/.*
    expiration: '1y'

  - url: /(.*\.(css|js|ico|png|jpg|jpeg|gif|svg|woff|woff2|ttf|eot))
    static_files: out/\1
    upload: out/.*\.(css|js|ico|png|jpg|jpeg|gif|svg|woff|woff2|ttf|eot)
    expiration: '1y'

  # Images and media files
  - url: /(.*\.(webp|mp4|webm|ogg|mp3|wav))
    static_files: out/\1
    upload: out/.*\.(webp|mp4|webm|ogg|mp3|wav)
    expiration: '30d'

  # All other requests go to index.html for client-side routing
  - url: /.*
    static_files: out/index.html
    upload: out/index.html
    expiration: '0m'
