service: default
runtime: nodejs20

automatic_scaling:
  min_instances: 0 # scale to zero when idle (free tier friendly)
  max_instances: 2 # limit max instances to control costs
  target_throughput_utilization: 0.8 # slightly higher utilization
  max_concurrent_requests: 80
inbound_services:
  - warmup

# Run the Next.js server so we can leverage SSR/SSG and next/image optimization
entrypoint: npm start

handlers:
  # Serve Next.js built client assets directly with long cache
  - url: /_next/static
    static_dir: .next/static
    secure: always
    expiration: '365d'

  # Let Next.js handle image optimization endpoint
  - url: /_next/image
    script: auto
    secure: always

  # Serve everything under public/ as static
  - url: /(.*\.(css|js|ico|png|jpg|jpeg|gif|svg|webp|mp4|webm|ogg|mp3|wav|woff|woff2|ttf|eot))
    static_files: public/\1
    upload: public/.*\.(css|js|ico|png|jpg|jpeg|gif|svg|webp|mp4|webm|ogg|mp3|wav|woff|woff2|ttf|eot)
    expiration: '30d'
    secure: always

  # All other routes handled by the Node server (Next.js)
  - url: /.*
    script: auto
    secure: always
